TrainingArgs:
  epochs: 10
  warmup_steps: 500
  train_batch_size_per_device: 1
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  evaluation_steps: 500
  save_steps: 1000000
  gradient_accumulation_steps: 16